/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Project = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'projectUrl' : IDL.Text,
  'techStack' : IDL.Vec(IDL.Text),
});
export const SocialMediaLink = IDL.Record({
  'url' : IDL.Text,
  'platform' : IDL.Text,
});
export const Profile = IDL.Record({
  'bio' : IDL.Text,
  'title' : IDL.Text,
  'background' : IDL.Text,
  'projects' : IDL.Vec(Project),
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'githubUrl' : IDL.Text,
  'socialMediaLinks' : IDL.Vec(SocialMediaLink),
  'avatarUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllPortfolios' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
  'getPortfolio' : IDL.Func([IDL.Principal], [Profile], ['query']),
  'setPortfolio' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Vec(Project),
        IDL.Vec(SocialMediaLink),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Project = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'projectUrl' : IDL.Text,
    'techStack' : IDL.Vec(IDL.Text),
  });
  const SocialMediaLink = IDL.Record({
    'url' : IDL.Text,
    'platform' : IDL.Text,
  });
  const Profile = IDL.Record({
    'bio' : IDL.Text,
    'title' : IDL.Text,
    'background' : IDL.Text,
    'projects' : IDL.Vec(Project),
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'githubUrl' : IDL.Text,
    'socialMediaLinks' : IDL.Vec(SocialMediaLink),
    'avatarUrl' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllPortfolios' : IDL.Func([], [IDL.Vec(Profile)], ['query']),
    'getPortfolio' : IDL.Func([IDL.Principal], [Profile], ['query']),
    'setPortfolio' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Vec(Project),
          IDL.Vec(SocialMediaLink),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };